# Generated by Django 2.0.6 on 2018-06-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20180621_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
